name: test

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm

      - name: install dependencies
        run: npm ci

      - name: install shfmt
        run: go install mvdan.cc/sh/v3/cmd/shfmt@latest

      - name: lint
        run: npm run lint

      - name: shellcheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: './src'
